name: invisibleobjects
favicon: null
layout_spectrum: 0.23777
typography_spectrum: 0.6774893233086914
title: Software for the entertainment industry
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#a0a0a0'
    - '#4b4b4b'
    - '#1783d0'
  brandStrength: 0.8874920206144452
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
