name: invisibleobjects
favicon: null
layout_spectrum: 0.3455986340995878
typography_spectrum: 0.6774893233086914
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8874920206144452
  lightness: 0.9736074826214463
  saturation: 0.2957594671752304
  rhythmicContrast: 0.27919352101162076
purpose: []
